apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
      - name: knote
        image: fabricio211/knote:1.4
        imagePullPolicy: Always
        env:
          - name: MONGO_URL
            value: mongodb://mongo:27017/dev
        resources:
          requests:
            memory: "350Mi"
            cpu: "100m"
          limits:
            memory: "350Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/info
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 40
          timeoutSeconds: 2
          failureThreshold: 30
          successThreshold: 1
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: knote-service
spec:
  type: NodePort
  selector:
    app: knote
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080